### PR TITLE
Copied platforms from finn-experimental and made pre-commit conform

### PR DESCRIPTION
**Pull request by HenniOVP**
Hi,
I copied the platform defentions from finn-experimental to finn-base to make them available in FINN. The original file in finn-experimental from which this commit was copied can be found here: https://github.com/Xilinx/finn-experimental/blob/f82c0d9868bb88ea045dfadb28508d327d287221/src/finn/util/platforms.py
Changes to the file were only made to confirm to the pre-commit hooks.

### CODE REVIEW

**Comment by maltanar** [comment]
@quetric as far as I can see this is straight from `finn-experimental` at the moment, do you think any changes are needed to this before it goes into `finn-base`? I see a few things in there re. the resource cost of the VNx stack for instance, I'm happy to keep this in `finn-base` but I wonder if this will introduce an extra step (e.g. if the VNx resource cost changes in a future version, first `finn-base` will have to be updated, then all derived repos have to update the commit #)

@fpjentzsch could you add the data for ZCU102 and ZCU111 to this please?

**Comment by fpjentzsch** [comment]
> @fpjentzsch could you add the data for ZCU102 and ZCU111 to this please?

@maltanar Done. While we are at it: Should I also add some code in the finn (not finn-base) entrypoint script to pull the ZCU111 board files (along with others?) from https://github.com/Xilinx/XilinxBoardStore? They do not seem to come with Vivado (2020.1)

**Comment by quetric** [comment]
@maltanar I'm okay with it going in as-is. It's unlikely for the VNx cost to change significantly in the future (it's quite stable right now). What is probably more likely is for a TCP option to be added at some point, but in any case I expect changes to this definition to be rare.

**Comment by maltanar** [comment]
> > @fpjentzsch could you add the data for ZCU102 and ZCU111 to this please?
> 
> @maltanar Done. While we are at it: Should I also add some code in the finn (not finn-base) entrypoint script to pull the ZCU111 board files (along with others?) from https://github.com/Xilinx/XilinxBoardStore? They do not seem to come with Vivado (2020.1)

@fpjentzsch yes please, that'd be great

**Pull request merged**
